FROM golang:1.18.2-alpine

ARG OS=linux
ARG ARCH=arm64
ARG PORT=10000

ENV GO111MODULE=on

WORKDIR /server

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=$OS GOARCH=$ARCH go build -o server

EXPOSE $PORT
ENTRYPOINT ["./server"]