FROM golang:1.18.2-alpine

ARG OS=linux
ARG ARCH=arm64
ARG PORT=10000

ENV GO111MODULE=on

WORKDIR /blog-server

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o server

EXPOSE 10000
ENTRYPOINT ["./server"]